apiVersion: apps/v1
kind: Deployment
metadata:
  name: quizz-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quizz-app
  template:
    metadata:
      labels:
        app: quizz-app
    spec:
      nodeSelector:
        app: quizz-app
      containers:
      - name: quiz-cont
        image: steja8494/quizz_app
        ports:
        - containerPort: 3000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-app
  template:
    metadata:
      labels:
        app: weather-app
    spec:
      nodeSelector:
        app: weather-app
      containers:
      - name: weather-cont
        image: steja8494/react_weather_app
        ports:
        - containerPort: 3000
      serviceAccountName: default
      imagePullSecrets:
      - name: docker-hub-credentials

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: quizz-app-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: quizz-app-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: weather-app-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: weather-app-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50

---

apiVersion: v1
kind: Service
metadata:
  name: quizz-app-service
spec:
  type: LoadBalancer
  selector:
    app: quizz-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: weather-app-service
spec:
  type: LoadBalancer
  selector:
    app: weather-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
